### PR TITLE
Implement several fixes

### PR DESCRIPTION
**Pull request by stolenbike**
This adds support for a Release Version number with 4 digits (Visual
Studio style) - a configurable support to switch between different
styles of version numbers has not been implemented yet

### CODE REVIEW

**Comment by zegenie** [comment]
This PR can no longer be merged cleanly. I'd like to improve the release numbering to support the functionality in the original PR, so please don't hesitate to make a new, clean PR.

**Comment by Rvanlaak** [comment]
@zegenie are you able to rebase and smash these commits into one? The "from `unknown repository`" is weird though.

**Comment by zegenie** [comment]
I wasn't sure which ones were still valid. I can't do it now, but if you're able to, feel free to squash / cherry-pick and create a new PR. I'll merge.

**Comment by zegenie** [comment]
The "unknown repository" part is because the repo the PR is based on has been deleted. Nothing mind-boggling ;)

**Comment by jtraulle** [comment]
I've tried to download the PR .patch https://github.com/thebuggenie/thebuggenie/pull/295.patch and to apply it to a clean branch checked out from up to date master with no luck ; sorry. :cry: 

If I have some time, I will try to re-apply manually changes listed from https://github.com/thebuggenie/thebuggenie/pull/295/files page :wink:

**Pull request closed without merging**
