### PR TITLE
Fixed api_list_issuefields failing to find json template.

### PR DESCRIPTION
**Pull request by founderio**
This fixes an issue I found, where an API call to /api/:api_username/list/issuefields/for/:project_key/type/:issuetype/:format would not find the template required.
I checked and found that it seems, listissuefields.json.php was just in the wrong place..

### CODE REVIEW

**Comment by rvanlaak** [comment]
Think it is time for a stable release, it has been a while @zegenie  ;-)

Maybe also add Travis and some integrity checks that will be tested with every PR? :+1:

**Comment by founderio** [comment]
While we're at it.. Any plans for the API? I'm in need for a stable API for a current project and might be able to contribute something :)

**Comment by zegenie** [comment]
@rvanlaak will release something stable as soon as we've got master stabilized ;)

@founderio any and all input on the api is most appreciated. Feel free to send me an email or raise an improvement issue in the tracker if you want to discuss it!

**Comment by founderio** [comment]
@zegenie Sure thing!
For reference, I have posted my collected thoughts here: http://issues.thebuggenie.com/thebuggenie/issues/2649

**Pull request merged**
