### PR TITLE
Additional fixes, improvements and additions for 4.1 version

### PR DESCRIPTION
**Pull request by Premke**
Notable changes:

- Added GitLab support for vcs integration module (fb141b4, 89cc623). These changes will be available in PR for that module also, though this project should require it as submodule
- Changed project commmits to use ajax for retrieving commits and added branch and repository filters (ae265ef)
- Added functionality when renaming manual wiki page to rename prefix of its subpages (fe850f3)
- Updated oxygen theme with changed layout for not fluid pages like configure and its subpages (bc32759)

### CODE REVIEW

**Comment by Rvanlaak** [comment]
Since you've been busy with the VCS integration, it seems like TBG does not assign commits to issues where the project has a prefix:

    SC-1239

or

    SC1239

or

    (SC1239)

Maybe you can elaborate on this?

**Comment by Premke** [comment]
@Rvanlaak Hmm it should, I'll look right into that.

**Comment by zegenie** [comment]
@rvanlaak @premke on that note there seems to be an issue if the prefix or
issue number is the first bit of the commit message as well.

**Comment by Rvanlaak** [comment]
We actually put the issue numbers at the end of the commit message. Did take a look at the quite overcomplex detection function a while ago, but it seems to be used by other modules.

**Comment by zegenie** [comment]
The detection function is there to extract issue numbers from anything, so
that you don't have to write the commit message in a specific format. Being
able to put issue numbers on the beginning means you can get a nicely
formatted list like:
 * PROJ-101 - fix something
 * PROJ-391 - fix something else

when looking at the git history. In any case, it should work regardless of
where and how you write the issue numbers, so let's not break anything here
:)

**Comment by Rvanlaak** [comment]
Not willing to break anything is why I didn't put any more effort in it :smile:

**Comment by Premke** [comment]
@Rvanlaak @zegenie Sorry for delay but It took some time setting everything up on github and codeanywhere for the test. So I tested various cases (check https://github.com/Premke/test-tbg-vcs-integration/commits/master and http://preview.vh80p1efawoh6w293mbyu5hyek2fn7b9hf4ya75os9qnnrk9.box.codeanywhere.com/tbg/public/testtbgvcsintegration/issues/TTVI-1) and everything works except for some minor unrelated problem fixed in commit 646b9b4da2a0654f8d4a2b0e96b56c1435379fc8.

**Pull request merged**
