### PR TITLE
New batch of version 4.1 fixes

### PR DESCRIPTION
**Pull request by Premke**
With this PR almost all of changes and fixed of project functionalities are covered. Permissions are checked thoroughly and we consider this version stable. 

Revision is bumped to 4.1.4 but we suggest it becomes 4.2.

### CODE REVIEW

**Comment by zegenie** [comment]
This doesn't merge cleanly with master :(

**Comment by Premke** [comment]
zegenie: Merge should be possible now, though i don't understand why Scrutinizer check failed, its Details are vague and Travis failed due to error with symlinking of "/themes/oxygen/css/publish.css" which is not altered in this PR.

**Comment by rvanlaak** [comment]
The symlink actually should be removed, because it is served via Assetic.

**Comment by Premke** [comment]
@rvanlaak Removed symlinked style files.

**Comment by rvanlaak** [comment]
Did the upgrade procedure, but the following error occurs:

    Unknown column 'projects31.issues_lock_type' in 'field list'

**Comment by Premke** [comment]
@rvanlaak Hmm it should work, could you try upgrading it again, commit 8fb9fb9a718f3d7e40863afebe69b0a0e1d629f5 added new column. When i tested in some cases second upgrade was necessary...

**Comment by bmudda** [comment]
@Premke upgrading again didn't fix the problem. Still get ```Unknown column 'projects31.issues_lock_type' in 'field list' ```

**Comment by Premke** [comment]
@bmudda PR #437 should fix this.

**Comment by bmudda** [comment]
@Premke yes PR #437 fixes the missing column bug. Thanks.

**Comment by Premke** [comment]
@bmudda Great :)

**Pull request merged**
