### PR TITLE
Quick fix for version upgrade

### PR DESCRIPTION
**Pull request by Premke**
Until better solution is implemented here is a quick fix for upgrading with versions in between 3.2 and 4.1.3.

### CODE REVIEW

**Comment by zegenie** [comment]
This is similar to, but the opposite of my install fix. Please change it so that version number is the entry point for the switch statement and then make sure all upgrades run in order without `break`ing. I know it's a quick fix but repeating all the upgrade steps per version is bound to cause issues later.
Thanks!

**Comment by Premke** [comment]
@zegenie Done in commit 33fc7abd7f9307d40d215e1b531a1649105a77a9.

**Comment by rvanlaak** [comment]
Squashing all these commits would be nice ;)

**Comment by Premke** [comment]
@rvanlaak Well i tried doing it from PhpStorm but due to lack of knowledge on how to do it i ended up using "Rebase my GitHub fork" (http://blog.jetbrains.com/idea/2011/02/advanced-github-integration-rebase-my-github-fork/) and here are more commits... :/

Could you give me some hint?

**Comment by rvanlaak** [comment]
Ghehe, yes it is terrible I know ;) You should rebase interactive against `thebuggenie/master` and then squash the commits in the dialog. Make sure to enable "force push" in the settings, and do a forced push afterwards. This will overwrite the Git history, so confirm the related warning :+1:

**Comment by zegenie** [comment]
I don't know why you would do force push. Never do force push if you don't
absolutely have to, since this will definitely cause issues for someone
else. I'd *much* rather have unsquashed commits than people randomly force
pushing.

**Comment by rvanlaak** [comment]
@zegenie how do you squash your commits without a forced push then?

**Comment by zegenie** [comment]
Why would you want to squash commits in an already pushed branch? Branches
are cheap - just make a new one based off the same point, cherry-pick the
commits you want, squash them before you push and make a new PR off that
branch instead.

On Thu, Nov 12, 2015 at 12:25 PM, Richard van Laak <notifications@github.com

**Comment by rvanlaak** [comment]
@Premke your latest master shows all milestones and it's related issues at the agile board (planning mode).

**Comment by Premke** [comment]
@rvanlaak I can't reproduce. Could you give me reproduction steps?

**Comment by rvanlaak** [comment]
I don't have any reproduction steps, it just occured right after I completed the upgrade. See screenshot:

milestones

**Comment by rvanlaak** [comment]
I do have a lot of other warnings in the console:

image

**Comment by Premke** [comment]
@rvanlaak Mind if we take this to IRC? If i can assume that milestone shouldn't be visible, but have you specifically marked it as finished or it has just reached its date? We might have broken functionality if it is used to be hidden when reached... Also i can't reproduce those errors with assets not being found. There was another commit ec5236339797973281f5f1b019c95d5e6d6a8d52 fixing some of my local changes that slipped into one of commits so you might try pulling that one first

**Comment by zegenie** [comment]
I'm gonna merge this so we get the installation fixes in and master isn't upgrade broken.

**Comment by rvanlaak** [comment]
Great! I'll test it now. Maybe make a `develop` branch again, and tag stable releases more often? :+1:

**Comment by rvanlaak** [comment]
The upgrade error is fixed, but the agile board still shows all milestones over here.

**Comment by zegenie** [comment]
Yeah, I think @Premke is on top of that.

**Comment by Premke** [comment]
@rvanlaak @zegenie I am :D

@rvanlaak Though it would be of great help if you could export some database records that could reproduce the problem and are not security risk to you...

**Comment by rvanlaak** [comment]
I'll try to make some reproduction for that, the data export is too big of a risk indeed ;-)

**Pull request merged**
