### PR TITLE
Fixes, improvements and additions for 4.1 version

### PR DESCRIPTION
**Pull request by Premke**
Functionality and visual fixes, improvements and opinionated additions.

Noticeable changes:
- Expand notification issue reference to include issue title (4d5576e)
- Added reset of poller lockers when ajax failed due to network problems (973dd1c)
- Added percentage completed indicator for whiteboard issues (99adaf5)
- Added spent points and hours count for issues on Whiteboard and Planning pages (48bdaac)
- Added and improved functionality of loading new and older notifications (959edcd, c9e5dba)
- Implemented Greensock's plugin "Draggable" on Whiteboard page to support touch enabled devices (a58a886)
- Matching file by filename in issue is done first against column "real_filename" and then "original_filename" (e15ca88)

### CODE REVIEW

**Comment by Rvanlaak** [comment]
:+1: nice new features!

What about adding [`BowerPHP`](http://bowerphp.org/) to install all frontend libraries? PRs like these are unnecessarily huge because of the libraries that are added. We can use the `composer post install` commands to easily include it in the installation process.

**Comment by Premke** [comment]
@Rvanlaak I aggree with you, some assets package manager should be used. Though we (LogosLabs) didn't want to introduce it as it might be too opinionated so we'll leave it up to @zegenie and community to decide. It should probably be done as a separate PR and cover installation for all package manager's supported assets.

Also if that PR becomes [WIP], we'll cover installation for assets introduced in our commits.

**Comment by Rvanlaak** [comment]
Yes, should be a separate PR. Will make a quick start after this PR was merged.

**Comment by Rvanlaak** [comment]
@zegenie what do you think about adding [`BowerPHP`](http://bowerphp.org/) and calling it in the composer install/update? This will remove quite some external libraries from the codebase.

**Comment by zegenie** [comment]
@Rvanlaak I think that's a great idea. Combined with composer, it'll make dependency handling much easier. There needs to be a way for modules to add dependencies, too.

**Comment by Rvanlaak** [comment]
You mean every module can have it's own `bower.json` file? The install script can loop through all modules for these.

**Comment by zegenie** [comment]
The best would be if all modules were self-contained with their own composer.json and bower.json files, but we need to support installing modules via the gui like today.

**Comment by Rvanlaak** [comment]
I think installing modules should be done via self containing packages, of which the installation process (eg. composer/bower) already was completed.

Just like I think should be done for TBG itself, every release should also have a installation file with the vendor packages already installed. :+1:  Ofcourse installing using composer is preferred, but non-cli users (shared hosting) now aren't able to easily install TBG.

**Comment by zegenie** [comment]
Of course, that makes sense.

**Pull request merged**
