### PR TITLE
Automation for setting-up development environment server using Vagrant and Ansible

### PR DESCRIPTION
**Pull request by azaghal**
Here is a relatively small implementation for setting-up a development environment server using Vagrant and Ansible.

There is also a couple of small changes to existing code to avoid committing wrong files into the repo (like thebuggenie.log).

Documentation has been written at (the page might needs updates and eventual move under the correct category on wiki to make it more visible):

http://issues.thebuggenie.com/wiki/TheBugGenie%3ADevelopment%3AVagrant

There could be a small catch with `ldap_entry.py` and `ldap_permissions.py` distributed with the tools in that they technically probably need to be under GPLv3 (since they do make calls to Ansible's internal API, and Ansible is GPLv3 too). Let me know if there's anything I need to do regarding that (they should not affect the license of Ansible itself in any way since they don't link against each-other).

### CODE REVIEW

**Comment by zegenie** [comment]
Great PR, and wonderful documentation. I do think there is an issue with distributing the ansible python scripts under our license, so is it possible to amend this with a script that can download these files separately, which also mentions the license difference? Running them together won't be an issue, but I don't want to be in the grey here.

**Comment by azaghal** [comment]
I'll try to have a look at it. Was thinking that in worst case I could do something less intelligent (just applying two LDIF's) at the expense of idempotency/flexibility. I don't think this will degrade functionality at all, and probably it would be better to have as little manual steps as possible (plus anyone trying to download the modules from my website will get a big fat certificate warning for now).

Once Ansible 2.3.0.0 comes out, it should have `ldap_entry` and `ldap_attr` modules out of the box that could be reused. Will update docs after this to make a note on both.

**Comment by azaghal** [comment]
Heh, the commit got added to pull request automatically, cool :)

Ok, fixed and updated the documentation. Same instructions should apply.

You mentioned updates to readme, should I add something specific to it apropos Vagrant/Ansible provisioning being shipped?

**Comment by zegenie** [comment]
Yes, please amend the readme with a section about the vagrant setup. For anyone wanting to just download and provision a box with TBG, this would be very helpful. I have had god experience using a separate repository for the ansible stuff which can pull down (check out or symlink) the repository - this could also get around the licensing issue since this separate repository can have a different license. What are your thoughts about this?

**Comment by azaghal** [comment]
Well, at least in this specific case (the LDAP-related modules in Ansible) I do not think it is worth it to have external dependency. I.e. the hack is pretty small, and Ansible will include native support for LDAP soon, so should be fine once that comes out.

I would assume that in this case it would be cheaper to keep Vagrant and Ansible playbooks within the same repo, given they are not that complex and that it means people can be up and running very quickly.

I'll add some notes to the README.

**Comment by azaghal** [comment]
Updated the README file.

**Comment by azaghal** [comment]
Yay :) Should I add link to the Vagrant page on [Category:The Bug Genie:Development](http://issues.thebuggenie.com/wiki/Category%3ATheBugGenie%3ADevelopment), and if so under what section you think it would fit best?

**Comment by zegenie** [comment]
I think having it as a separate Howto would make sense, and maybe just see if you can combine it with one of the other items on that page either under a new heading or make a separate heading for it.

**Comment by azaghal** [comment]
I've added a link to "Recommended reading" for now.

**Pull request merged**
