### PR TITLE
New polished Oxygen theme, installation visual fixes and functionality fixes

### PR DESCRIPTION
**Pull request by Premke**

### CODE REVIEW

**Comment by Rvanlaak** [comment]
:+1: my PR with the Assetic implementation is on it's way

**Comment by Premke** [comment]
@Rvanlaak Awesome, the more automated and modular developing the better. I think at bug genie current state of code Assetic is preferable over Gulp since its written in PHP...
@zegenie What are your thoughts on this? Are there any plans for sass / less support?

**Comment by Rvanlaak** [comment]
see #396

**Comment by Premke** [comment]
@Rvanlaak  Nice PR :+1: 

I think discussion for assets filters should be probably done in IRC or new PR.

**Pull request merged**
