### PR TITLE
Yet additional fixes, improvements and additions for 4.1 version

### PR DESCRIPTION
**Pull request by Premke**
Commit db362fc is affecting PR #425 so I'll elaborate more on this commit there.

Biggest change is introduction of check if user can set status in transition (commits d92186f and 36dd073). Errors on transition are now shown for ajax calls too. Before these commits if you could not set status manually, you could do it via transition, which defeats the purpose of permission.

### CODE REVIEW

**Comment by Premke** [comment]
@zegenie Permission checks for other datatypes could be implemented but I'm not sure how to structure it without changing too much codebase. I had an idea of using Traits but it would impose php v5.4 as requirement. Therefore I'll leave it up to you.

**Comment by Rvanlaak** [comment]
What about annotations or about triggering events?

**Comment by zegenie** [comment]
@Premke how did you plan on solving the permission checking with traits? Could it be done by modifying customdatatype and/or datatypebase?

@Rvanlaak how would you suggest using annotations to solve this?

As a final note, I'm not entirely convinced 5.3 compatibility is a must.

**Comment by Rvanlaak** [comment]
A trait is just another way of injecting the class with extra functionality right? The difference is that traits allow you to add functionality when the parent's implementation is unknown.

The annotation could define the permission checker relation to the datatype, the checker could be initialized in `b2db` and can be directly mapped to the implementation since we exactly know the datatype's implementation.

**Comment by zegenie** [comment]
Having generic permissions checking defined via annotations will probably be very difficult to get right, mostly because of the way project permissions work, and the inheritance of group / role permissions. It would be a nice experiment, and I'd definitely review a PR that implemented it.

I know what traits are, just wondering how he'd solve it using them :)

**Comment by Rvanlaak** [comment]
Non-generic permissions could work via annotations on controller or action level? But maybe it's a bit overkill.

**Comment by zegenie** [comment]
This PR reintroduces the scrolling error in the notification dropdown for firefox.

**Comment by Premke** [comment]
@Rvanlaak @zegenie I abandoned my idea with traits, as annotations and / or events are in my opinion better suited for current codebase. Though I have no idea how to accomplish wanted functionality with those.

@zegenie About scrolling error I'll quote my response from IRC: 
> I couldn't reproduce visual bug with http://imgur.com/zYjJTEg, feel free to change styles since I don't know what changes from this PR caused it

It occurred to me that maybe content of your notifications is pushing width and thus x scroll is shown.

**Pull request merged**
