### PR TITLE
Some Fixes for buggenie

### PR DESCRIPTION
**Pull request by Yehonal**

### CODE REVIEW

**Comment by Yehonal** [comment]
Please could someone check this pull-request?

**Comment by zegenie** [comment]
commit 897c431 and 8797737 cancel eachother out, and a3dac06 is a merge commit. Could you make a clean PR with just the changes you want to implement - that'd be lot easier to review :) thanks!

**Comment by Yehonal** [comment]
Thanks for your reply.
What i've to do to clean my PR? I never did before :)

**Comment by Rvanlaak** [comment]
That would be a rebase against master, you can squash all your commits into one.

**Comment by Yehonal** [comment]
I've removed useless commits , but i prefer to not squash in a single commits since they are for difference purpose and moreover you can easily revert some of them in future if you need ( i hope not ).

Take a look

**Comment by zegenie** [comment]
Sorry for the delay, and thanks for all the fish .. err fixes :)

**Comment by zegenie** [comment]
Also, don't worry about the commits being squashed, I much prefer smaller commits which do one thing than bigger commits that does several things at once.

**Comment by Yehonal** [comment]
Thanks zegenie

However i'm trying to contact you for some information ( and to report a big security bug that i'm trying to fix ) via:
email -> no replies
the buggenie platform -> can't login
the forum -> can't register
the irc chat -> seems an abandoned

Is buggenie a death project? i hope someone could reply at least to this comment.

**Pull request merged**
