### PR TITLE
Work on API Overhaul

### PR DESCRIPTION
**Pull request by founderio**
This PR includes first forays into issue [#2649](http://issues.thebuggenie.com/thebuggenie/issues/2649)
It includes output optimization of the list commands (listprojects, listissuetypes and listfieldvalues) to have better compatibility & a new route that returns a basic status overview of the bug genie.
It's only a small step but I would like to have an opinion if I am going the right way with this.

EDIT:
There is now a central toJSON($detailed = false) function on various common entities that can be overridden by subclasses. (See Commit f35394c) Implementations form various entities are also included.
Also, Endpoint /me now prints out detailed information on the user currently logged in & accessing the API.

### CODE REVIEW

**Comment by Premke** [comment]
Nice changes, although in my opinion these API breaking changes should be versioned (as you did) but should also be backwards compatible via version parameter.

One way to do both things would be to version API before your changes and add version as parameter directly in url. 
For example "/api/1.0.0/:api_username/projects" would return projects before your output optimization so that apps depending on old output don't break. While "/api/:api_username/projects" with ommited version would default to latest API. Minor version could also be optional.

New endpoints as status overview you added should be available in all versions while modified would be resolved to correct method name based on API version.

Some kind of API changelog should probably exist in remote module. Also once remote module gets upgrade procedure changelog could be displayed before upgrading.

@founderio At LogosLabs fork we were fixing problems with current API version and planned for these kind of changes, it would be great if you could consider them also. Fixes will arrive in next PR.
Also good job on status overview endpoint, i really like it. :+1: 

@zegenie What's your opinion? Have you had any plans for remote module?

**Comment by founderio** [comment]
@Premke Sure, versioning sounds reasonable. That way we could do more "drastic" changes if required.

When we apply Semantic Versioning, Major Version would suffice I think.
Every change that breaks backwards compatibility would then result in a version increment. The minor version (and ultimately revision, too) would be purely informational for the client, to see if a new endpoint is available in that specific version or not.

Which means we would have at least two separate API versions more or less maintained in parallel.
That should be agreed on before we do anything rash here.

Question by the way, to anyone: Is there ANY existing documentation on the "new" API? I have only found docs for TBG 3. It would be nice if I had something to work with rather than start documenting from scratch. But documentation needs to be done, so if there is none, I will start putting something together.

**Comment by Premke** [comment]
Since API stayed the same from v3 I think there is no new documentation. I have read your issue [#2649](http://issues.thebuggenie.com/thebuggenie/issues/2649) and other similar issues there and I quite like your proposition. 

Unfortunately LogosLabs can't currently help out with implementing or documenting it since our efforts with fork are less focused on API.

Here is PR #449 mentioned in previous comment.

**Comment by founderio** [comment]
The only docs I have found are here: http://issues.thebuggenie.com/wiki/TheBugGenie%3ADevelopment%3AJsonAPI
True, some parts are quite similar, but at least the authentication part changed quite a bit with the application passwords...

Thanks for having a look! Any help is appreciated - even if it is mostly comments and nudges where to go :)

**Comment by Premke** [comment]
@founderio You are welcome, for quick comment or nudge pm me on IRC.

**Comment by rvanlaak** [comment]
Think the entire documentation could get a major overhaul. Next to that, it would be nice to have way more howto articles.

**Comment by zegenie** [comment]
First of all, thanks for taking the time to start this endeavour, it's
something that is much needed. I have some specific comments on your
commits, but github won't let me sign in, so please take them below:

I think for a first attempt, this is decent, but if I was to rewrite or
significantly improve the api integration, I would go all in. Before you
start off, keep in mind that there is no official TBG api, so any backwards
breaking changes is not really a dealbreaker just yet. Hopefully, we can
get a v1 out of this, but for now, don't worry about backwards
compatibility.

As for the approach with listing out details for things like issutypes,
etc, please follow the pattern from `entities\Issue`, using a `toJSON()`
method. This way, it's not up to the remote module to decide the json
representation of the objects, and it can be reused across TBG. It should
be possible to add a `toJSON()` method in `entities\Keyable`, which many
basic datatypes inherit - adding instant json representations for most TBG
internal datatypes - then extend the `toJSON()` method in subclasses as
necessary.

I very much like the idea of the status endpoint detailing latest api
version, but I think it can be entirely placed in the `remote` submodule,
including the version numbers. To be honest, except the changes made to
some of the entities, there's no reason why this module cannot be external
altogether. Let me know if you want help with that.

**Comment by zegenie** [comment]
First of all, thanks for taking the time to start this endeavour, it's something that is much needed. I have some specific comments on your commits, but github won't let me sign in, so please take them below:

I think for a first attempt, this is decent, but if I was to rewrite or significantly improve the api integration, I would go all in. Before you start off, keep in mind that there is no official TBG api, so any backwards breaking changes is not really a dealbreaker just yet. Hopefully, we can get a v1 out of this, but for now, don't worry about backwards compatibility.

As for the approach with listing out details for things like issutypes, etc, please follow the pattern from `entities\Issue`, using a `toJSON()` method. This way, it's not up to the remote module to decide the json representation of the objects, and it can be reused across TBG. It should be possible to add a `toJSON()` method in `entities\Keyable`, which many basic datatypes inherit - adding instant json representations for most TBG internal datatypes - then extend the `toJSON()` method in subclasses as necessary.

I very much like the idea of the status endpoint detailing latest api version, but I think it can be entirely placed in the `remote` submodule, including the version numbers. To be honest, except the changes made to some of the entities, there's no reason why this module cannot be external altogether. Let me know if you want help with that.

**Comment by founderio** [comment]
Hey @zegenie,
alright, I will take this into consideration and adjust the code.
I think I will add an additional (optional, default to false) parameter to switch on/off detail mode. As we don't need full detail when listing the available projects but would want such details if we query for a single project, that should make it easier.

I would appreciate help once it comes to the "internals" of TBG. I have poked around the code for quite some time but I cannot claim to know it very well.
If we pull out the remote plugin that would make versioning later quite easy - just create a "new" plugin. We'd only need to figure out an elegant way to add a prefix to each route.

**Comment by founderio** [comment]
Alright, that should do it for these `toJSON($detailed = false)` methods.
Tested locally, I have not found anything out of the order.

While looking into implementing the endpoint `/projects/:project_key` I came across a problem.
With the current method of specifying /:format at the end, this might cause an issue. Would calling `/projects/json` (`/projects/:format`) not be equivalent of calling `/projects/json` (`/projects/:project_key/:format`) with implicit format 'html'?
Can we prevent that or should I just move the :format to the front like `/api/:format/:api_username/projects` ?

**Comment by zegenie** [comment]
@founderio I don't think specifying :format as a mandatory parameter on each route is a good approach - I'm sorry if my previous comment(s) made it appear that way. To be honest, I think it is better to either:
* make the route use "dot format", as in `/api/something.:format`, or
* default to json format, unless otherwise requested via an `Accepts` header.

The `:format` parameter can default to json using a `_preExecute()` method in the remote module. This method runs automatically before every route, and is already used in other places. Regardless of which approach we choose, I don't think there will be many uses for the api in formats besides json at the moment. In those cases we can worry about adding additional formats later.

**Comment by zegenie** [comment]
As an additional comment, I would suggest moving the module to the external modules folder and distributing it as a separate module through the addons section on the website. If you want to, I can set up a separate repository for this, or we can use a different one. I also suggest we rename to module to simply be called API (lowercase ofcourse), to be less ambiguous (what does "remote" even mean?)

**Comment by rvanlaak** [comment]
Having an API module would be great :+1:  Especially because they can be updated on multiple occasions and don't have to stick to the monolithic TBG releases. :wink:

**Comment by founderio** [comment]
Hmm, I think now that we have the chance to make it "right", we should keep the format from the request url. The Accepts-header seems like a logical choice for me - defaulting to JSON if not specified. Although a manual override ?format=json should be possible for clients that don't support setting request headers.

For the Accept-Header can we have a config file (formats.yml ? ) that maps from "application/json" to "json" for template resolution?
That way anyone who desperately needs the info in "application/x-myownstuff+xml" can add their own templates and be done with it.

Regarding separate repo: Yep, sounds good to separate it.
If you want to open up a repo, go ahead!

I suspect that we need a Components.php and API.php?

**Comment by zegenie** [comment]
I'll make a separate repo with the `remote` module installable and renamed as `api`. Just gimme a few minutes :)

**Comment by zegenie** [comment]
I've created the repository now. Please fork and pull. There's also a separate subproject for the api module, here: http://issues.thebuggenie.com/module-api

**Comment by founderio** [comment]
Sure :+1: 
Umm, can you open the issue here: http://issues.thebuggenie.com/module-api/issues/API-1 ?
It redirects me to the search page.. I moved the old one to that project..

**Pull request merged**
