### PR TITLE
Guest captcha implementation for master branch (#2352)

### PR DESCRIPTION
**Pull request by azaghal**
I've gotten around and implemented the guest captcha in master branch now (this is more or less port from 3.2 branch).

Some small changes have been made in order to make the captcha input look a bit better on different pages, so there is a bit of redundant code. I don't think it can be fixed that easily, though, since different parts of TBG use different ways to present data.

### CODE REVIEW

**Comment by azaghal** [comment]
There's at least one minor thing I want to fix (the spurious logging) before this gets merged. I'll get back to you once I'm done with it :)

**Comment by zegenie** [comment]
How's this coming along? :)

**Comment by azaghal** [comment]
A bit slower than it should... I'll try to get some concentration to finish it off.

**Comment by zegenie** [comment]
I have to close this now as it can no longer be merged cleanly and there hasn't been any updates for a while. Could you please make a new PR if you manage to make this work properly?

**Comment by azaghal** [comment]
Sure, no problem.

**Comment by Rvanlaak** [comment]
Rebasing on master would also solve that
Op 15 apr. 2015 11:11 schreef "Branko Majic" <notifications@github.com>:

**Pull request closed without merging**
