### PR TITLE
"Create new users" handling proposal

### PR DESCRIPTION
**Pull request by stolenbike**
When creating a new user by the "More details" dialog, the dialog
(backdrop) stays open, even when the user were created successfully.
This is very confusing because most of the time the user expects that
the backdrop closes after a successful creation. This will be added by this small fix (if wanted)

### CODE REVIEW

**Comment by zegenie** [comment]
No sweat. I'll wait for an updated PR, then, before I merge ;)

**Comment by Premke** [comment]
Hiding Add a User Backdrop functionality was broken with my commit b7d14572d4c6758013975ca5c9ff85adcd801d6c, because I removed lines 57-61 since they were also causing dialog to appear on successful Quick add User.

As @zegenie suggested putting the toggle on successful callback will solve it and not cause problem with Quick add User functionality.

@stolenbike If you want I can make PR since it was me who broke it in the first place.

**Comment by stolenbike** [comment]
Go ahead - I am completely fine with that. Thanks! :)

**Comment by stolenbike** [comment]
Since Premke will do a fix I close this PR!

**Pull request closed without merging**
